[build]
  functions = "netlify/functions"

[[scheduled-functions]]
  name = "report-cron"
  schedule = "0 12 * * 1-5"

[[scheduled-functions]]
  name = "morning-cron"
  schedule = "0 20 * * 2-6"
[functions]
  node_bundler = "esbuild"

[functions."analyze"]
  timeout = 26
